### ISSUE TITLE
copy the kubectl out of the hyperkube docker container

### ISSUE THREAD

**Issue by mbruzek** [mbruzek/layer-k8s#35]
I believe that the hyperkube container has the kubectl and in an effort to reduce the reliance on the network we should copy the kubectl binary from the container (that could be delivered with resources).

**Comment by lazypower** [comment]
I like this idea. 👍

**Comment by mbruzek** [comment]
As it turns out we are pulling hyperkube, an "all in one binary" that runs kubectl, kubelet, proxy etc. So we can not just pull the kubectl out of the container.
